#!/usr/bin/perl
# \@author: beto0607
# It creates a folder with the name passed in the first param
# Inside that folder creates a __tests__ folder with $ARGV[0]-test.js inside
# Also creates a mains jsx file, a CSS Module and SASS file and a package.json file 
# I use that package.json file for improve the import of the generated module ( based on https://www.sitepoint.com/react-architecture-best-practices/ )
#
# Example: 
# current_dir 
#    └── Example
#        ├── __tests__
#        │   └── Example-test.js
#        ├── Example.jsx
#        └── Example.module.scss
 
use strict;
use warnings;

if ($#ARGV + 1 < 1 ) {
	print "You must provide the new container's name in the first paramenter";
	exit;
}
my $container_name = ucfirst($ARGV[0]);

#Create main folder
mkdir($container_name);
chdir($container_name);

#Create jsx file
open (FILE, '>'.$container_name.'.jsx');
print FILE "//\@author: beto0607\n";
print FILE "//generated by create_container\n\n";
print FILE "import React from 'react';\n";
print FILE "import styles from './".$container_name.".module.scss';\n";
print FILE "\n";
print FILE "class ".$container_name." extends React.Component{\n";
print FILE "\n";
print FILE "}\n";
print FILE "export default ".$container_name.";\n";
close FILE;

#Create package.json
open (FILE, '>package.json');
print FILE "{\n";
print FILE "\t\"main\": \"".$container_name.".jsx\"\n";
print FILE "}\n";
close FILE;
#Create CSS Module/SASS file
open FILE, '>'.$container_name.'.module.scss';
print FILE "#\@author: beto0607\n";
print FILE "#generated by create_container\n";
close FILE;
#Create __tests__ folder
mkdir('__tests__');
#Create test.js
open (FILE, '>__tests__/'.$container_name.'-tests.js');
print FILE "//\@author: beto0607\n";
print FILE "//generated by create_container\n";
