#!/usr/bin/perl
# \@author: beto0607
# It creates a React component structure with the name passed in the first param.
# It will try to access to ./src/components or ./components and create the component there. If it fails, the component will be created in the current folder.
# Inside that folder creates a __tests__ folder with $ARGV[0]-test.js inside
# Also creates a mains tsx file, a CSS Module and SASS file and a package.json file 
# I use that package.json file for improve the import of the generated module ( based on https://www.sitepoint.com/react-architecture-best-practices/ )
#
# Example: 
# current_dir 
#    └── Example
#        ├── __tests__
#        │   └── Example-test.js
#        ├── Example.tsx
#        └── Example.module.scss
 
use strict;
use warnings;

if ($#ARGV + 1 < 1 ) {
	print "You must provide the new container's name in the first paramenter.\n";
	exit;
}
# If current work dir is the project root folder it goes to src
chdir("src");
# If current work dir is "src" it creates the module in components folder
chdir("components");

my $component_name = ucfirst($ARGV[0]);

#Create main folder
print "Creating $component_name folder...\n";
mkdir($component_name);
chdir($component_name);

#Create tsx file
print "Creating $component_name.tsx file...\n";
open (FILE, '>'.$component_name.'.tsx');
print FILE qq#//\@author: beto0607\n#;
print FILE "//generated by create_container\n\n";
print FILE "import React from 'react';\n";
print FILE "import styles from './".$component_name.".module.scss';\n";
print FILE "\n";
print FILE "const ".$component_name." : React.RC = ({props, children}) => {\n";
print FILE "\n";
print FILE "\treturn (<h1>$component_name</h1>);\n";
print FILE "\n";
print FILE "}\n";
print FILE "export default ".$component_name.";\n";
close FILE;

#Create package.json
print "Creating package.json file...\n";
open (FILE, '>package.json');
print FILE "{\n";
print FILE "\t\"main\": \"".$component_name.".tsx\"\n";
print FILE "}\n";
close FILE;
#Create CSS Module/SASS file
print "Creating $component_name.module.scss file...\n";
open FILE, '>'.$component_name.'.module.scss';
print FILE "/*\@author: beto0607*/\n";
print FILE "/*generated by create_container*/\n";
close FILE;
#Create __tests__ folder
print "Creating __tests__ folder...\n";
mkdir('__tests__');
#Create test.ts
print "Creating $component_name-tests.ts file...\n";
open (FILE, '>__tests__/'.$component_name.'-tests.ts');
print FILE "//\@author: beto0607\n";
print FILE "//generated by create_container\n";
close FILE;

# End message
print "Component \"$component_name\" created.\n";
